# Generated by Django 4.2.3 on 2023-08-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDA', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='heading',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
